### PR TITLE
WIP for container view

### LINKED ISSUE #55: As a child, I want the game to look fun (EST 8)

### PR DESCRIPTION
**Pull request by N-Wouda**
TODO:

- [x]  Container view: 
    - [x] Perishability;
    - [x] Quantity

Closes #55.

### CODE REVIEW

**Comment by N-Wouda** [comment]
@LCfP/serious-logistics-games-for-kids guys, how do we quantify the perishability of a (food) product in a container? A progress bar of sorts, but how and where?

Any thoughts would be appreciated.

**Comment by lisavancasteren** [comment]
A progress bar would be nice, but could get confusing with so many products...
I also liked the categories (I think Luc mentioned them?) like fresh, still good, etc. Maybe divide the products in a rack per 'freshness category'? The least fresh products on top to emphasize these, most fresh at the bottom. This could provide some oversight?

**Comment by N-Wouda** [comment]
Perhaps a background color going from ['green', 'yellow', 'red']-ish to indicate [good, okay-ish, almost gone]?

We could underlay the color subtly for each product image, and not use this for non-perishable products.

**Comment by lisavancasteren** [comment]
Yeah nice! Those colors would be better than words indeed. Doing this for
every product won't make it too confusing/crowded?

**Comment by N-Wouda** [comment]
I think that might be true, but I'd first have to see before I can say anything definitive. I hope to have a first version perhaps tomorrow, I'll show pictures.

If it proves too much, we can always make the coloring a bit more subtle, so I think we will be okay! :)

**Comment by lisavancasteren** [comment]
Great! Curious how it will turn out :)

**Comment by N-Wouda** [comment]
perishabilityoverlay

This is what I have now, @lisavancasteren.

**Comment by N-Wouda** [comment]
This is pretty much ready, that is, the container view part.

The customer/customer order and history parts still need to be done, but I don't think I'll find the time anymore to do so this sprint.

**Pull request merged**
